# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_bill_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='\u540d\u5b57')),
                ('url', models.URLField(blank=True, null=True, verbose_name='\u5b98\u7f51')),
                ('city', models.CharField(blank=True, choices=[('Paris,France', '\u5df4\u9ece'), ('Reims,France', '\u5170\u65af'), ('Dijon,France', '\u7b2c\u620e'), ('Tour,France', '\u56fe\u5c14'), ('Bordeaux,France', '\u6ce2\u5c14\u591a'), ('Avignon,France', '\u963f\u7ef4\u5c3c\u7fc1'), ('Nice,France', '\u5c3c\u65af'), ('Marseille,France', '\u9a6c\u8d5b'), ('Roman,Italy', '\u7f57\u9a6c'), ('Milan,Italy', '\u7c73\u5170'), ('Geneva,Switzerland', '\u65e5\u5185\u74e6'), ('Prague,Czekh', '\u5e03\u62c9\u683c')], max_length=15, null=True, verbose_name='\u76ee\u7684\u5730')),
                ('comment', models.TextField(verbose_name='\u5907\u6ce8')),
                ('open_sun', models.BooleanField(default=False, verbose_name='\u5468\u65e5\u5f00\u95e8')),
                ('open_sat', models.BooleanField(default=False, verbose_name='\u5468\u516d\u5f00\u95e8')),
                ('level', models.CharField(blank=True, choices=[('very-easy', '\u975e\u5e38\u5bb9\u6613'), ('easy', '\u5bb9\u6613'), ('middle', '\u4e00\u822c'), ('hard', '\u56f0\u96be'), ('very-hard', '\u51e0\u4e4e\u4e0d\u53ef\u80fd')], max_length=15, null=True, verbose_name='\u9884\u7ea6\u96be\u5ea6')),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='city',
            field=models.CharField(blank=True, choices=[('Paris,France', '\u5df4\u9ece'), ('Reims,France', '\u5170\u65af'), ('Dijon,France', '\u7b2c\u620e'), ('Tour,France', '\u56fe\u5c14'), ('Bordeaux,France', '\u6ce2\u5c14\u591a'), ('Avignon,France', '\u963f\u7ef4\u5c3c\u7fc1'), ('Nice,France', '\u5c3c\u65af'), ('Marseille,France', '\u9a6c\u8d5b'), ('Roman,Italy', '\u7f57\u9a6c'), ('Milan,Italy', '\u7c73\u5170'), ('Geneva,Switzerland', '\u65e5\u5185\u74e6'), ('Prague,Czekh', '\u5e03\u62c9\u683c')], max_length=15, null=True, verbose_name='\u65c5\u6e38\u76ee\u7684\u5730'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_send_plan',
            field=models.BooleanField(default=False, verbose_name='\u5df2\u53d1\u884c\u7a0b\u63d0\u9192'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_send_wether',
            field=models.BooleanField(default=False, verbose_name='\u5df2\u53d1\u5929\u6c14\u63d0\u9192'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='travel_date',
            field=models.DateField(verbose_name='\u51fa\u53d1\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='person',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=60, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='\u7535\u8bdd'),
        ),
    ]
