# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20160325_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castle',
            name='level',
            field=models.CharField(blank=True, choices=[('\u975e\u5e38\u5bb9\u6613', '\u975e\u5e38\u5bb9\u6613'), ('\u5bb9\u6613', '\u5bb9\u6613'), ('\u4e00\u822c', '\u4e00\u822c'), ('\u56f0\u96be', '\u56f0\u96be'), ('\u51e0\u4e4e\u4e0d\u53ef\u80fd', '\u51e0\u4e4e\u4e0d\u53ef\u80fd')], max_length=15, null=True, verbose_name='\u9884\u7ea6\u96be\u5ea6'),
        ),
    ]
