# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-29 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20160325_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contract', models.CharField(max_length=20, verbose_name='\u8ba2\u5355\u53f7')),
                ('client_name', models.CharField(max_length=40, verbose_name='\u5ba2\u6237\u59d3\u540d')),
                ('client_wechat', models.CharField(max_length=20, verbose_name='\u5ba2\u6237\u5fae\u4fe1')),
                ('client_phone', models.CharField(max_length=15, verbose_name='\u5ba2\u6237\u624b\u673a')),
                ('client_passport', models.CharField(max_length=15, verbose_name='\u5ba2\u6237\u62a4\u7167')),
                ('trip_info', models.TextField(verbose_name='\u9884\u8ba2\u9879\u76ee')),
                ('num_person', models.IntegerField(verbose_name='\u51fa\u6e38\u4eba\u6570')),
                ('trip_date', models.DateField(verbose_name='\u51fa\u53d1\u65e5\u671f')),
                ('due', models.TextField(verbose_name='\u6536\u8d39\u60c5\u51b5')),
                ('reception', models.TextField(verbose_name='\u63a5\u9001\u4fe1\u606f')),
                ('contact_emergency', models.CharField(max_length=50, verbose_name='\u7d27\u6025\u8054\u7cfb\u4eba')),
                ('call_center_name', models.CharField(max_length=20, verbose_name='\u5ba2\u670d\u59d3\u540d')),
                ('call_center_phone', models.CharField(max_length=20, verbose_name='\u5ba2\u670d\u7535\u8bdd')),
                ('call_center_wechat', models.CharField(max_length=20, verbose_name='\u5ba2\u670d\u5fae\u4fe1')),
                ('trip_comment', models.TextField(verbose_name='\u5907\u6ce8\u63d0\u793a')),
            ],
        ),
    ]
